### ISSUE TITLE
Приблема с приемкой флагов 

### ISSUE THREAD

**Issue by sea5kg** [shipko/ctf-attack-defense#8]
```
/home/sea-kg/.local/lib/python3.5/site-packages/pymongo/topology.py:143: UserWarning: MongoClient opened before fork. Create MongoClient with connect=False, or create client after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#using-pymongo-with-multiprocessing>
  "MongoClient opened before fork. Create MongoClient "
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sea-kg/develop/ctfight/ctf-attack-defense.git/classes/flags.py", line 68, in recv
    self.process_one_team(connection, team)
  File "/home/sea-kg/develop/ctfight/ctf-attack-defense.git/classes/flags.py", line 74, in process_one_team
    connection.send(('Welcome! \nYour team - ' + team["name"] + '\n').encode())
TypeError: 'bool' object is not subscriptable
```

**Comment by shipko** [comment]
Не установлен клиент MongoDB. Написал install.sh и подробную инструкцию
